env: APP_ENV
httpport: APP_HTTPPORT
keypath:
  publicKey: APP_KEYPATH_PUBLICKEY
  privateKey: APP_KEYPATH_PRIVATEKEY
database:
  postgresDB:
    host: APP_DATABASE_POSTGRESDB_HOST
    port: APP_DATABASE_POSTGRESDB_PORT
    username: APP_DATABASE_POSTGRESDB_USERNAME
    password: APP_DATABASE_POSTGRESDB_PASSWORD
    dbName: APP_DATABASE_POSTGRESDB_DBNAME
    sslMode: APP_DATABASE_POSTGRESDB_SSLMODE
gcp:
  serviceAccount: APP_GCP_SERVICEACCOUNT
  projectID: APP_GCP_PROJECTID
