env: local
httpport: 8080
keypath:
  publicKey: ./cert/public/public.pem
  privateKey: ./cert/private/private.pem
gcp:
  serviceAccount: ./cert/service_account/service_account.json
  projectID: lenswear-service
